/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelEntrarRouteImport } from './routes/painel/entrar'
import { Route as ApiDemoResetRouteImport } from './routes/api/demo/reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelEntrarRoute = PainelEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => PainelRouteRoute,
} as any)
const ApiDemoResetRoute = ApiDemoResetRouteImport.update({
  id: '/api/demo/reset',
  path: '/api/demo/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/painel/entrar': typeof PainelEntrarRoute
  '/painel/': typeof PainelIndexRoute
  '/api/demo/reset': typeof ApiDemoResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel/entrar': typeof PainelEntrarRoute
  '/painel': typeof PainelIndexRoute
  '/api/demo/reset': typeof ApiDemoResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/painel/entrar': typeof PainelEntrarRoute
  '/painel/': typeof PainelIndexRoute
  '/api/demo/reset': typeof ApiDemoResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel' | '/painel/entrar' | '/painel/' | '/api/demo/reset'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel/entrar' | '/painel' | '/api/demo/reset'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/painel/entrar'
    | '/painel/'
    | '/api/demo/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  ApiDemoResetRoute: typeof ApiDemoResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/entrar': {
      id: '/painel/entrar'
      path: '/entrar'
      fullPath: '/painel/entrar'
      preLoaderRoute: typeof PainelEntrarRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/api/demo/reset': {
      id: '/api/demo/reset'
      path: '/api/demo/reset'
      fullPath: '/api/demo/reset'
      preLoaderRoute: typeof ApiDemoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteRouteChildren {
  PainelEntrarRoute: typeof PainelEntrarRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelEntrarRoute: PainelEntrarRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  ApiDemoResetRoute: ApiDemoResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
